#!/bin/bash

if [ -f ~/jenkins.war ]
then
	echo 'Redis package already exists.  Deleting...'
	rm -rf redis-stable.tar.gz redis-stable
	echo 'done.'
fi

echo 'Installing Redis.'

# download the latest version of Redis
wget http://download.redis.io/redis-stable.tar.gz
# unzip the package
tar xvzf redis-stable.tar.gz
cd redis-stable
# install Redis
make

# copy scripts to the user's home directory
echo 'Installing to dotCloud.'
cd ..
cp -a redis-latest/. ~